In [13]:
import pandas as pd
import numpy as np
import zipfile

### pytrends dataframe, NY weekly google trends for keywords

In [2]:
#pytrends for Google Trends
from pytrends.request import TrendReq
import pandas as pd


pytrends = TrendReq(hl='en-US', tz=360)

# looking for these keywords
keywords = ["asthma attack", "asthma inhaler", "difficulty breathing"]
# location
pytrends.build_payload(keywords, geo='US-NY', timeframe='2025-01-01 2025-12-31')

trendsdf = pytrends.interest_over_time()

In [3]:
trendsdf.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 53 entries, 2024-12-29 to 2025-12-28
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   asthma attack         53 non-null     int64
 1   asthma inhaler        53 non-null     int64
 2   difficulty breathing  53 non-null     int64
 3   isPartial             53 non-null     bool
dtypes: bool(1), int64(3)
memory usage: 1.7 KB

In [4]:
trendsdf.head(10)

            asthma attack  asthma inhaler  difficulty breathing  isPartial
date
2024-12-29             90              61                    38      False
2025-01-05             71              51                    47      False
2025-01-12             66              50                    51      False
2025-01-19             53              33                    40      False
2025-01-26             72              61                    40      False
2025-02-02             66              56                    48      False
2025-02-09             69              76                    56      False
2025-02-16             75              66                    52      False
2025-02-23             76              66                    56      False
2025-03-02             61              46                    44      False

### csv containing AQI and air pollution data

In [ ]:
# using zipfile module as MAC seems to add an additional csv file when zipping a csv
with zipfile.ZipFile('../data/AQI_Geo.zip') as z:
    with z.open('AQI_Geo.csv') as f:
        asthmadf = pd.read_csv(f)

/var/folders/3y/ldxff8k17wjcyzkq19xw1srm0000gn/T/ipykernel_8867/181032678.py:9: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  asthmadf = pd.read_csv(f)

In [15]:
# filtered dataframe to be just for new york city
asthmadf = asthmadf[(asthmadf['State Name'] == 'New York') & (asthmadf['City Name'] == 'New York')]

In [20]:
display(asthmadf.info())

<class 'pandas.core.frame.DataFrame'>
Index: 5026 entries, 270434 to 279187
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State Code           5026 non-null   int64
 1   County Code          5026 non-null   int64
 2   Site Num             5026 non-null   int64
 3   Parameter Code       5026 non-null   int64
 4   POC                  5026 non-null   int64
 5   Latitude             5026 non-null   float64
 6   Longitude            5026 non-null   float64
 7   Datum                5026 non-null   object
 8   Parameter Name       5026 non-null   object
 9   Sample Duration      5026 non-null   object
 10  Pollutant Standard   2760 non-null   object
 11  Date Local           5026 non-null   object
 12  Units of Measure     5026 non-null   object
 13  Event Type           0 non-null      object
 14  Observation Count    5026 non-null   int64
 15  Observation Percent  5026 non-null   int64
 16  Arithmetic Mean      5026 non-null   float64
 17  1st Max Value        5026 non-null   float64
 18  1st Max Hour         5026 non-null   int64
 19  AQI                  2760 non-null   float64
 20  Method Code          5026 non-null   int64
 21  Method Name          5026 non-null   object
 22  Local Site Name      5026 non-null   object
 23  Address              5026 non-null   object
 24  State Name           5026 non-null   object
 25  County Name          5026 non-null   object
 26  City Name            5026 non-null   object
 27  CBSA Name            5026 non-null   object
 28  Date of Last Change  5026 non-null   object
dtypes: float64(5), int64(9), object(15)
memory usage: 1.2+ MB

None

In [21]:
display(asthmadf.head(10))

,State Code,County Code,Site Num,Parameter Code,POC,Latitude,Longitude,Datum,Parameter Name,Sample Duration,...,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change
270434,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,29.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270435,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,9.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270436,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,16.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270437,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,28.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270438,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,55.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270439,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,51.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270440,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,42.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270441,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,56.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270442,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,55.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25
270443,36,5,110,88101,1,40.816,-73.902,WGS84,PM2.5 - Local Conditions,24 HOUR,...,33.0,145,R & P Model 2025 PM-2.5 Sequential Air Sampler...,IS 52,IS 52 681 KELLY ST,New York,Bronx,New York,"New York-Newark-Jersey City, NY-NJ-PA",10/15/25